export const BIBLE_BOOKS = [
  ["genesis", "창세기", "old"],
  ["exodus", "출애굽기", "old"],
  ["leviticus", "레위기", "old"],
  ["numbers", "민수기", "old"],
  ["deuteronomy", "신명기", "old"],
  ["joshua", "여호수아", "old"],
  ["judges", "사사기", "old"],
  ["ruth", "룻기", "old"],
  ["1-samuel", "사무엘상", "old"],
  ["2-samuel", "사무엘하", "old"],
  ["1-kings", "열왕기상", "old"],
  ["2-kings", "열왕기하", "old"],
  ["1-chronicles", "역대상", "old"],
  ["2-chronicles", "역대하", "old"],
  ["ezra", "에스라", "old"],
  ["nehemiah", "느헤미야", "old"],
  ["esther", "에스더", "old"],
  ["job", "욥기", "old"],
  ["psalms", "시편", "old"],
  ["proverbs", "잠언", "old"],
  ["ecclesiastes", "전도서", "old"],
  ["song-of-songs", "아가", "old"],
  ["isaiah", "이사야", "old"],
  ["jeremiah", "예레미야", "old"],
  ["lamentations", "예레미야애가", "old"],
  ["ezekiel", "에스겔", "old"],
  ["daniel", "다니엘", "old"],
  ["hosea", "호세아", "old"],
  ["joel", "요엘", "old"],
  ["amos", "아모스", "old"],
  ["obadiah", "오바댜", "old"],
  ["jonah", "요나", "old"],
  ["micah", "미가", "old"],
  ["nahum", "나훔", "old"],
  ["habakkuk", "하박국", "old"],
  ["zephaniah", "스바냐", "old"],
  ["haggai", "학개", "old"],
  ["zechariah", "스가랴", "old"],
  ["malachi", "말라기", "old"],
  ["matthew", "마태복음", "new"],
  ["mark", "마가복음", "new"],
  ["luke", "누가복음", "new"],
  ["john", "요한복음", "new"],
  ["acts", "사도행전", "new"],
  ["romans", "로마서", "new"],
  ["1-corinthians", "고린도전서", "new"],
  ["2-corinthians", "고린도후서", "new"],
  ["galatians", "갈라디아서", "new"],
  ["ephesians", "에베소서", "new"],
  ["philippians", "빌립보서", "new"],
  ["colossians", "골로새서", "new"],
  ["1-thessalonians", "데살로니가전서", "new"],
  ["2-thessalonians", "데살로니가후서", "new"],
  ["1-timothy", "디모데전서", "new"],
  ["2-timothy", "디모데후서", "new"],
  ["titus", "디도서", "new"],
  ["philemon", "빌레몬서", "new"],
  ["hebrews", "히브리서", "new"],
  ["james", "야고보서", "new"],
  ["1-peter", "베드로전서", "new"],
  ["2-peter", "베드로후서", "new"],
  ["1-john", "요한일서", "new"],
  ["2-john", "요한이서", "new"],
  ["3-john", "요한삼서", "new"],
  ["jude", "유다서", "new"],
  ["revelation", "요한계시록", "new"],
] as const;

export const DAILY_VERSES = [
  { reference: "시편 23:1", text: "여호와는 나의 목자시니 내게 부족함이 없으리로다." },
  { reference: "잠언 3:5", text: "너는 마음을 다하여 여호와를 신뢰하고 네 명철을 의지하지 말라." },
  { reference: "이사야 41:10", text: "두려워하지 말라 내가 너와 함께 함이라." },
  { reference: "예레미야 29:11", text: "너희를 향한 나의 생각을 내가 아나니 평안이요 재앙이 아니니라." },
  { reference: "마태복음 11:28", text: "수고하고 무거운 짐 진 자들아 다 내게로 오라." },
  { reference: "요한복음 15:5", text: "나는 포도나무요 너희는 가지라." },
  { reference: "로마서 8:28", text: "하나님을 사랑하는 자 곧 그의 뜻대로 부르심을 입은 자들에게는 모든 것이 합력하여 선을 이루느니라." },
  { reference: "고린도전서 16:14", text: "너희 모든 일을 사랑으로 행하라." },
  { reference: "갈라디아서 6:9", text: "선한 일을 하다가 낙심하지 말지니." },
  { reference: "빌립보서 4:6", text: "아무 것도 염려하지 말고 다만 모든 일에 기도와 간구로." },
  { reference: "빌립보서 4:13", text: "내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라." },
  { reference: "골로새서 3:23", text: "무슨 일을 하든지 마음을 다하여 주께 하듯 하고 사람에게 하듯 하지 말라." },
  { reference: "데살로니가전서 5:16-18", text: "항상 기뻐하라 쉬지 말고 기도하라 범사에 감사하라." },
  { reference: "디모데후서 1:7", text: "하나님이 우리에게 주신 것은 두려워하는 마음이 아니요." },
  { reference: "히브리서 11:1", text: "믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거니." },
  { reference: "야고보서 1:5", text: "너희 중에 누구든지 지혜가 부족하거든 하나님께 구하라." },
  { reference: "베드로전서 5:7", text: "너희 염려를 다 주께 맡기라." },
  { reference: "요한일서 4:19", text: "우리가 사랑함은 그가 먼저 우리를 사랑하셨음이라." },
];
